# 张量和数据类型

In [1]:
import torch
import numpy as np

## 初始化张量

### 从Python列表初始化张量

In [2]:
t = torch.tensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


In [3]:
t = torch.tensor([1., 2., 3.])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [4]:
t = torch.FloatTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [5]:
t = torch.LongTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


### 从numpy的ndarray初始化

In [6]:
np_array = np.arange(12).reshape(3, 4)
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
t = torch.from_numpy(np_array)
# 也可以使用下面的方式
# t = torch.tensor(np_array)
print(t)
print(t.dtype)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)
torch.int32


## 张量（Tensor）基本数据类型

* 32位浮点型：torch.float32 / torch.float
* 64位浮点型：torch.float64
* 64位整型： torch.int64 / torch.long
* 32位整型： torch.int32
* 16位整型： torch.int16

In [8]:
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [9]:
t = torch.tensor([1, 2, 3], dtype=torch.float)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [10]:
t = torch.tensor([1, 2, 3], dtype=torch.long)
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


## 创建随机值张量

In [11]:
# 创建（0，1）之间均匀分布的随机数
t = torch.rand(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[0.2249, 0.5454, 0.2282, 0.2156],
        [0.5188, 0.1689, 0.1999, 0.6528],
        [0.9461, 0.3551, 0.8195, 0.0513]])
torch.float32
torch.Size([3, 4])


In [ ]:
# 创建标准正态分布的随机数
t = torch.randn(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[-1.0345, -0.1888, -1.2674,  1.2076],
        [-0.0485,  0.2700,  0.2747, -0.9227],
        [-1.7699, -0.2620,  1.8283,  0.9572]])
torch.float32
torch.Size([3, 4])


In [ ]:
# 创建全0的张量
t = torch.zeros(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
torch.Size([3, 4])


In [ ]:
# 创建全1的张量
t = torch.ones(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.Size([3, 4])


In [ ]:
# 创建一个与t形状相同的张量，但是值是正态分布的随机数
t = torch.randn_like(t)
print(t)
print(t.dtype)
print(t.shape)

tensor([[-1.6008,  1.9314,  0.6021, -0.8916],
        [ 0.0655,  0.1578, -0.5806, -1.2603],
        [ 1.0721,  1.0485, -0.9114,  0.1952]])
torch.float32
torch.Size([3, 4])


## 张量的属性

In [ ]:
# 创建一个与t形状相同的张量，但是值是在（0，1）均匀分布的随机数
t = torch.rand_like(t)
print(t)
# 返回张量的数据类型
print(t.dtype)
# 返回张量的形状
print(t.shape)
print("size = " + str(t.size()))
# 返回张量的维度
print("dim = " + str(t.dim()))
# 返回张量第一个维度的长度
print("size(0) = " + str(t.size(0)))
# 返回张量第二个维度的长度
print("size(1) = " + str(t.size(1)))
# 返回张量的元素个数
print("numel= " + str(t.numel()))


tensor([[0.1050, 0.8983, 0.5441, 0.1269],
        [0.8557, 0.9037, 0.5279, 0.7686],
        [0.8533, 0.5117, 0.6555, 0.4139]])
torch.float32
torch.Size([3, 4])
size = torch.Size([3, 4])
dim = 2
size(0) = 3
size(1) = 4
numel= 12


In [1]:
import torch

In [ ]:
x = torch.rand(2, 3)
print(x)

In [ ]:
x = torch.randn(2, 3)
print(x)

In [ ]:
x = torch.zeros(2, 3)
print(x)

In [ ]:
x = torch.ones(2, 3)
print(x)

In [ ]:
x.size()

In [ ]:
x.shape

In [ ]:
x = torch.tensor([6, 2])
print(x)

In [ ]:
x.size()

### 数据类型

In [ ]:
x = torch.tensor([6, 2], dtype=torch.float32)
print(x)

In [ ]:
x.type(torch.int64)

In [ ]:
x = torch.ones(2, 3, dtype=torch.float64)
print(x)

### 与ndarray数据类型的转换

In [52]:
import numpy as np

In [53]:
a = np.random.randn(2, 3)

In [ ]:
a

In [55]:
x1 = torch.from_numpy(a)

In [ ]:
x1

In [ ]:
x1.numpy()

张量运算

In [ ]:
x + x1

In [ ]:
x

In [ ]:
x + 3

In [ ]:
x.add(x1)

In [ ]:
x.add_(x1)

In [ ]:
x

In [ ]:
x.view(3, 2)

In [ ]:
x.view(-1, 1)

In [67]:
x = x.mean()

In [ ]:
x

In [ ]:
x.item()

### 张量的自动微分

将Torch.Tensor属性 .requires_grad 设置为True，

pytorch将开始跟踪对此张量的所有操作。

完成计算后，可以调用 .backward() 并自动计算所有梯度。

该张量的梯度将累加到.grad属性中。

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

In [ ]:
x.requires_grad

In [111]:
x.grad

In [112]:
x.grad_fn   # 指向运算生成此张量的方法

In [ ]:
# 进行张量运算
y = x + 2
print(y)

In [ ]:
# y是由于运算而创建的，因此具有grad_fn属性

print(y.grad_fn)

In [ ]:
# 进行更多操作

z = y * y * 3
out = z.mean()

print(z, out)

### 计算梯度

In [116]:
out.backward()    # 自动微分运算, 注意 out 是标量值

打印梯度  d（out）/ dx   

out = f(x)

In [ ]:
print(x.grad)

In [ ]:
x.data

In [107]:
x.grad_fn

当张量的 requires_grad 属性为 True 时， 

pytorch会一直跟踪记录此张量的运算

当不需要跟踪计算时，可以通过将代码块包装在  with torch.no_grad(): 上下文中

In [ ]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

也可使用 .detach() 来获得具有相同内容但不需要跟踪运算的新Tensor ：

In [ ]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

In [ ]:
x.data

In [ ]:
x.detach()

使用 requires_grad_ 就地改变张量此属性

In [ ]:
a = torch.randn(2, 2)
a = a*3 + 2
print(a.requires_grad)

In [ ]:
a.requires_grad_(True)
print(a.requires_grad)

总结 pytorch 张量的数据结构形式