# 张量和数据类型

In [1]:
import torch
import numpy as np

## 初始化张量

### 从Python列表初始化张量

In [2]:
t = torch.tensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


In [3]:
t = torch.tensor([1., 2., 3.])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [4]:
t = torch.FloatTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [5]:
t = torch.LongTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


### 从numpy的ndarray初始化

In [6]:
np_array = np.arange(12).reshape(3, 4)
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
t = torch.from_numpy(np_array)
# 也可以使用下面的方式
# t = torch.tensor(np_array)
print(t)
print(t.dtype)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)
torch.int32


## 张量（Tensor）基本数据类型

* 32位浮点型：torch.float32 / torch.float
* 64位浮点型：torch.float64
* 64位整型： torch.int64 / torch.long
* 32位整型： torch.int32
* 16位整型： torch.int16

In [8]:
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [9]:
t = torch.tensor([1, 2, 3], dtype=torch.float)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [10]:
t = torch.tensor([1, 2, 3], dtype=torch.long)
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


## 创建随机值张量

In [11]:
# 创建（0，1）之间均匀分布的随机数
t = torch.rand(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[0.1177, 0.6748, 0.9072, 0.0814],
        [0.1240, 0.2105, 0.2115, 0.6189],
        [0.2297, 0.3468, 0.1999, 0.2457]])
torch.float32
torch.Size([3, 4])


In [12]:
# 创建标准正态分布的随机数
t = torch.randn(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[-1.8310,  1.3585, -0.4829, -1.7086],
        [ 0.1540, -0.0939,  1.5591,  0.2789],
        [-1.9121, -0.2894,  0.0938, -0.4290]])
torch.float32
torch.Size([3, 4])


In [13]:
# 创建全0的张量
t = torch.zeros(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
torch.Size([3, 4])


In [14]:
# 创建全1的张量
t = torch.ones(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.Size([3, 4])


In [15]:
# 创建一个与t形状相同的张量，但是值是正态分布的随机数
t = torch.randn_like(t)
print(t)
print(t.dtype)
print(t.shape)

tensor([[-0.5983,  0.6046, -0.3986,  0.2813],
        [ 0.9636, -0.3125,  0.2171, -0.9225],
        [-1.6047,  1.1522, -0.5084, -0.2563]])
torch.float32
torch.Size([3, 4])


## 张量的属性

In [16]:
# 创建一个与t形状相同的张量，但是值是在（0，1）均匀分布的随机数
t = torch.rand_like(t)
print(t)
# 返回张量的数据类型
print(t.dtype)
# 返回张量的形状
print(t.shape)
print("size = " + str(t.size()))
# 返回张量的维度
print("dim = " + str(t.dim()))
# 返回张量第一个维度的长度
print("size(0) = " + str(t.size(0)))
# 返回张量第二个维度的长度
print("size(1) = " + str(t.size(1)))
# 返回张量的元素个数
print("numel= " + str(t.numel()))


tensor([[0.5385, 0.3000, 0.1955, 0.9011],
        [0.0987, 0.3806, 0.6554, 0.5518],
        [0.7518, 0.0090, 0.0065, 0.1747]])
torch.float32
torch.Size([3, 4])
size = torch.Size([3, 4])
dim = 2
size(0) = 3
size(1) = 4
numel= 12


## 张量存储设备及其转移

In [17]:
# 返回张量的存储设备
print("device = " + str(t.device))
print("torch.cuda.is_available() = " + str(torch.cuda.is_available()))
# 将张量转移到GPU
if torch.cuda.is_available():
    t = t.to('cuda')
    print("device = " + str(t.device))

device = cpu
torch.cuda.is_available() = True
device = cuda:0


In [18]:
# 将张量转移到CPU
t = t.to('cpu')
print("device = " + str(t.device))

device = cpu


## 张量数据类型的转换

In [19]:
# 对张量进行数据类型转换
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)
print("----------------")
t = t.type(torch.float64)
print(t)
print(t.dtype)
print("----------------")
t = t.type(torch.int64)
print(t)
print(t.dtype)


tensor([1., 2., 3.])
torch.float32
----------------
tensor([1., 2., 3.], dtype=torch.float64)
torch.float64
----------------
tensor([1, 2, 3])
torch.int64


In [20]:
t = torch.randn(3, 4)
print(t)
print(t.dtype)
print("----------------")
# .long()方法可以将张量转换为64位整型，即int64，与t.type(torch.int64)等价
t = t.long()
print(t)
print(t.dtype)
print("----------------")
# .int()方法可以将张量转换为32位整型
# .short()方法可以将张量转换为16位整型
# .char()方法可以将张量转换为8位整型
# .byte()方法可以将张量转换为8位无符号整型

# .double()方法可以将张量转换为64位浮点型
# .float()方法可以将张量转换为32位浮点型
t = t.float()
print(t)
print(t.dtype)
print("----------------")
# .half()方法可以将张量转换为16位浮点型

# .bool()方法可以将张量转换为布尔型

tensor([[-1.6259,  0.4243,  0.0878,  0.7511],
        [-2.0375, -0.1314,  2.0351, -0.1543],
        [-0.9781,  0.7493,  0.0953, -0.6086]])
torch.float32
----------------
tensor([[-1,  0,  0,  0],
        [-2,  0,  2,  0],
        [ 0,  0,  0,  0]])
torch.int64
----------------
tensor([[-1.,  0.,  0.,  0.],
        [-2.,  0.,  2.,  0.],
        [ 0.,  0.,  0.,  0.]])
torch.float32
----------------


## 张量运算

In [21]:
# 加法：广播原则
t1 = torch.randn(3, 4)
print(t1)
# 数值与t1相加，每个元素加3
print(t1 + 3)
print("----------------")
# 与相同形状的张量相加,对应元素相加；与不同形状的张量相加，会报错
t2 = torch.randn(3, 4)
print(t2)
# print(t1 + t2)
# print(torch.add(t1, t2))
#等同于
print(t1.add(t2))   # t1的值不变
print("----------------")
print(t1)
print(t1.add_(t2))      # t1 = t1 + t2
# t1的值改变
print(t1)
print("----------------")
# 方法后面带下划线的方法会改变调用者的值
# 类似的方法还有sub（减法）、mul（乘法）、div（除法）、pow（幂运算）、sqrt（开方）
# log（对数运算）、exp（指数运算）、abs（绝对值）、neg（取负数）、reciprocal（取倒数）
# mean（求均值）、std（求标准差）、var（求方差）、norm（求范数）
# max（求最大值）、min（求最小值）、argmax（求最大值索引）、argmin（求最小值索引）
# sum（求和）、prod（求积）、cumsum（求累加和）、cumprod（求累乘积）
# round（四舍五入）、floor（向下取整）、ceil（向上取整）、trunc（取整数部分）、frac（取小数部分）等

tensor([[-1.7161, -2.0000,  0.0601, -0.0810],
        [ 1.4729,  1.7963,  1.6105, -1.2821],
        [ 2.3197,  0.3561,  1.5493,  0.1468]])
tensor([[1.2839, 1.0000, 3.0601, 2.9190],
        [4.4729, 4.7963, 4.6105, 1.7179],
        [5.3197, 3.3561, 4.5493, 3.1468]])
----------------
tensor([[ 0.7928,  0.1617,  0.6632,  0.4048],
        [ 0.9433,  0.0438,  1.1499,  1.4722],
        [-1.4397, -0.5393, -0.2915,  1.1260]])
tensor([[-0.9233, -1.8383,  0.7233,  0.3238],
        [ 2.4162,  1.8402,  2.7604,  0.1901],
        [ 0.8800, -0.1832,  1.2579,  1.2728]])
----------------
tensor([[-1.7161, -2.0000,  0.0601, -0.0810],
        [ 1.4729,  1.7963,  1.6105, -1.2821],
        [ 2.3197,  0.3561,  1.5493,  0.1468]])
tensor([[-0.9233, -1.8383,  0.7233,  0.3238],
        [ 2.4162,  1.8402,  2.7604,  0.1901],
        [ 0.8800, -0.1832,  1.2579,  1.2728]])
tensor([[-0.9233, -1.8383,  0.7233,  0.3238],
        [ 2.4162,  1.8402,  2.7604,  0.1901],
        [ 0.8800, -0.1832,  1.2579,  1.2728]])
-----

In [22]:
# matmul（矩阵乘法）、@（矩阵乘法）、T（转置）、transpose（转置）、permute（维度交换）、reshape（形状变换）、view（形状变换）
t1 = torch.randn(3, 4)
print(t1)
print(t1.T)
print(t1.matmul(t1.T))

tensor([[ 1.0902,  0.5554, -1.7102, -1.7215],
        [ 0.0922,  0.4974,  0.3530,  0.3055],
        [ 0.3642,  1.6786,  0.7084, -1.7233]])
tensor([[ 1.0902,  0.0922,  0.3642],
        [ 0.5554,  0.4974,  1.6786],
        [-1.7102,  0.3530,  0.7084],
        [-1.7215,  0.3055, -1.7233]])
tensor([[ 7.3855, -0.7530,  3.0844],
        [-0.7530,  0.4739,  0.5921],
        [ 3.0844,  0.5921,  6.4219]])


## 从张量转换为python和numpy的数据类型

In [23]:
# 转换为Python数据类型
t2 = t1.sum()
print(t2)
print(t2.item())        # 将张量的值转换为Python数值
print(t1.tolist())      # 将张量的值转换为Python列表
result = t1.mean()      # 求均值
print(result)           # 返回一个张量
print(result.item())    # 返回一个Python数值

tensor(0.4899)
0.4899040460586548
[[1.0902432203292847, 0.5553516745567322, -1.7102121114730835, -1.721518874168396], [0.09216282516717911, 0.4974042773246765, 0.35304132103919983, 0.30552318692207336], [0.3641728460788727, 1.6786128282546997, 0.7084041237831116, -1.7232813835144043]]
tensor(0.0408)
0.040825337171554565


In [24]:
# 转换为Numpy数据类型
# 从Numpy数组创建张量
np_array = np.random.randn(3, 4)
print(np_array)
t = torch.from_numpy(np_array)
print(t)
# 将张量转换为Numpy数组
# .numpy()方法可以将张量转换为Numpy数组
np_array = t.numpy()
print(np_array)


[[ 1.41883279 -0.95257798 -0.18890659 -0.48641482]
 [ 0.42616922 -1.59641941 -1.76066375 -0.48706198]
 [ 0.26104462  0.24526234  0.56820306 -0.94299848]]
tensor([[ 1.4188, -0.9526, -0.1889, -0.4864],
        [ 0.4262, -1.5964, -1.7607, -0.4871],
        [ 0.2610,  0.2453,  0.5682, -0.9430]], dtype=torch.float64)
[[ 1.41883279 -0.95257798 -0.18890659 -0.48641482]
 [ 0.42616922 -1.59641941 -1.76066375 -0.48706198]
 [ 0.26104462  0.24526234  0.56820306 -0.94299848]]


## 张量的变形

In [25]:
t = torch.randn(3, 4)
print(t)
print(t.shape)
# .view()方法可以改变张量的形状，但是张量的元素个数不能改变
t1 = t.view(4, 3)
print(t1)
print(t1.shape)
# .reshape()方法与.view()方法功能相同

tensor([[-1.6793, -0.8542,  0.7689,  0.1314],
        [-0.0092,  1.2937,  0.2664,  0.3984],
        [ 1.5437, -0.2328, -0.2579,  1.8050]])
torch.Size([3, 4])
tensor([[-1.6793, -0.8542,  0.7689],
        [ 0.1314, -0.0092,  1.2937],
        [ 0.2664,  0.3984,  1.5437],
        [-0.2328, -0.2579,  1.8050]])
torch.Size([4, 3])


In [26]:
# 常用于展平张量
t = torch.randn(3, 4)
print(t)
print(t.shape)
# 转换为第二维度为1的张量，-1表示自动计算
t1 = t.view(-1, 1)  #即将t展平为 24 * 1 的张量
print(t1)
print(t1.shape)
# 例如
t = torch.randn(12, 3, 4, 4)
print(t.shape)
# 将t展平为 12 * 48 的张量
t1 = t.view(12, -1)
# 也可写为
t1 = t.view(12, 48)  # 12 * 3 * 4 * 4 = 12 * 48
print(t1.shape)

tensor([[ 0.7381, -0.2125, -0.3387,  0.6400],
        [-0.8849, -0.0879, -0.1936, -1.4546],
        [-1.1767,  1.2316, -0.4358, -0.4991]])
torch.Size([3, 4])
tensor([[ 0.7381],
        [-0.2125],
        [-0.3387],
        [ 0.6400],
        [-0.8849],
        [-0.0879],
        [-0.1936],
        [-1.4546],
        [-1.1767],
        [ 1.2316],
        [-0.4358],
        [-0.4991]])
torch.Size([12, 1])
torch.Size([12, 3, 4, 4])
torch.Size([12, 48])


In [27]:
# 给张量增加一个维度，例如将形状为(3, 4)的张量增加一个维度，形状变为(1, 3, 4)
t = torch.randn(3, 4)
print(t)
print(t.shape)
# .unsqueeze()方法可以增加张量为1的维度
t1 = t.unsqueeze(0) # 在第0维度增加一个维度
print(t1)
print(t1.shape)
# 也可以写为
# t1 = t.view(1, 3, 4)
# print(t1)
# print(t1.shape)

# 给张量减少一个维度
# .squeeze()方法可以减少张量为1的维度
t2 = t1.squeeze()
print(t2)
print(t2.shape)

tensor([[-0.3296,  0.8689,  0.1442,  0.7353],
        [ 0.2953,  0.1210, -0.6175,  0.8944],
        [-0.2386,  1.3840,  0.0905,  0.8804]])
torch.Size([3, 4])
tensor([[[-0.3296,  0.8689,  0.1442,  0.7353],
         [ 0.2953,  0.1210, -0.6175,  0.8944],
         [-0.2386,  1.3840,  0.0905,  0.8804]]])
torch.Size([1, 3, 4])
tensor([[-0.3296,  0.8689,  0.1442,  0.7353],
        [ 0.2953,  0.1210, -0.6175,  0.8944],
        [-0.2386,  1.3840,  0.0905,  0.8804]])
torch.Size([3, 4])


## 张量的自动微分

In [28]:
t = torch.randn(3, 4)
print(t.requires_grad) # tensor的requires_grad属性默认为False， 表示不需要Pytorch自动跟踪
t.requires_grad = True # 设置requires_grad属性为True，Pytorch将开始跟踪对此张量的所有操作
print(t.requires_grad) 

False
True


1. 将Torch.Tensor属性 .requires_grad 设置为True，pytorch将开始跟踪对此张量的所有操作。

2. 完成计算后，可以调用 .backward() 并自动计算所有梯度。该张量的梯度将累加到.grad属性中。

In [29]:
t = torch.ones(3, 4, requires_grad=True) # 创建一个requires_grad属性为True的张量
print(t)
print(t.requires_grad)
x = t + 5
print(x)
print(x.grad_fn)        # grad_fn属性表示张量的创建方式，x是通过加法操作创建的
print(x.requires_grad)  # x会继承t的requires_grad属性
y = x * 2
print(y)
print(y.grad_fn)        # y是通过乘法操作创建的
print(y.requires_grad)  # y会继承x的requires_grad属性
z = y.mean()            # 求y的均值, z是一个标量值，维度为0
print(z)
print(z.grad_fn)        # z是通过mean操作创建的
print(z.requires_grad)  # z会继承y的requires_grad属性
z.backward()        # 反向传播，自动微分运算，计算梯度
print(t.grad)       # t.grad属性保存了t的梯度，dz/dt = 1/12
print(t.grad_fn)    # t.grad_fn属性为None，因为t是用户创建的张量，不是通过操作创建的
print(z.grad_fn)    # z.grad_fn属性为MeanBackward0，表示z是通过mean操作创建的


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)
True
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]], grad_fn=<AddBackward0>)
True
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]], grad_fn=<MulBackward0>)
True
tensor(12., grad_fn=<MeanBackward0>)
True
tensor([[0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667]])
None


### 张量的自动微分

将Torch.Tensor属性 .requires_grad 设置为True，

pytorch将开始跟踪对此张量的所有操作。

完成计算后，可以调用 .backward() 并自动计算所有梯度。

该张量的梯度将累加到.grad属性中。

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

In [ ]:
x.requires_grad

In [69]:
x.grad

In [70]:
x.grad_fn   # 指向运算生成此张量的方法

In [ ]:
# 进行张量运算
y = x + 2
print(y)

In [ ]:
# y是由于运算而创建的，因此具有grad_fn属性

print(y.grad_fn)

In [ ]:
# 进行更多操作

z = y * 2
out = z.mean()

print(z, out)

### 计算梯度

In [ ]:
out.backward()    # 自动微分运算, 注意 out 是标量值

打印梯度  d（out）/ dx   

out = f(x)

In [ ]:
print(x.grad)

In [ ]:
x.data

In [77]:
x.grad_fn

当张量的 requires_grad 属性为 True 时， 

pytorch会一直跟踪记录此张量的运算

当不需要跟踪计算时，可以通过将代码块包装在  with torch.no_grad(): 上下文中

In [ ]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

也可使用 .detach() 来获得具有相同内容但不需要跟踪运算的新Tensor ：

In [ ]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

In [ ]:
x.data

In [ ]:
x.detach()

使用 requires_grad_ 就地改变张量此属性

In [ ]:
a = torch.randn(2, 2)
a = a*3 + 2
print(a.requires_grad)

In [ ]:
a.requires_grad_(True)
print(a.requires_grad)

总结 pytorch 张量的数据结构形式