# 张量和数据类型

In [1]:
import torch
import numpy as np

## 初始化张量

### 从Python列表初始化张量

In [2]:
t = torch.tensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


In [3]:
t = torch.tensor([1., 2., 3.])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [4]:
t = torch.FloatTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [5]:
t = torch.LongTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


### 从numpy的ndarray初始化

In [6]:
np_array = np.arange(12).reshape(3, 4)
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
t = torch.from_numpy(np_array)
# 也可以使用下面的方式
# t = torch.tensor(np_array)
print(t)
print(t.dtype)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)
torch.int32


## 张量（Tensor）基本数据类型

* 32位浮点型：torch.float32 / torch.float
* 64位浮点型：torch.float64
* 64位整型： torch.int64 / torch.long
* 32位整型： torch.int32
* 16位整型： torch.int16

In [8]:
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [9]:
t = torch.tensor([1, 2, 3], dtype=torch.float)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [10]:
t = torch.tensor([1, 2, 3], dtype=torch.long)
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


## 创建随机值张量

In [11]:
# 创建（0，1）之间均匀分布的随机数
t = torch.rand(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[0.2254, 0.9175, 0.9124, 0.5380],
        [0.3210, 0.5005, 0.2288, 0.5626],
        [0.7224, 0.9528, 0.2287, 0.1949]])
torch.float32
torch.Size([3, 4])


In [12]:
# 创建标准正态分布的随机数
t = torch.randn(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[-0.1930, -0.5222, -0.2073, -0.4694],
        [ 0.9427, -0.4022,  0.3850,  0.4793],
        [ 1.1780, -0.2818,  0.1137, -0.9878]])
torch.float32
torch.Size([3, 4])


In [13]:
# 创建全0的张量
t = torch.zeros(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
torch.Size([3, 4])


In [14]:
# 创建全1的张量
t = torch.ones(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.Size([3, 4])


In [15]:
# 创建一个与t形状相同的张量，但是值是正态分布的随机数
t = torch.randn_like(t)
print(t)
print(t.dtype)
print(t.shape)

tensor([[-0.2649, -0.7559, -0.9817,  0.0631],
        [-1.5281, -0.5442, -0.2271, -1.1772],
        [ 1.0725,  0.1528,  1.1123,  0.6684]])
torch.float32
torch.Size([3, 4])


## 张量的属性

In [16]:
# 创建一个与t形状相同的张量，但是值是在（0，1）均匀分布的随机数
t = torch.rand_like(t)
print(t)
# 返回张量的数据类型
print(t.dtype)
# 返回张量的形状
print(t.shape)
print("size = " + str(t.size()))
# 返回张量的维度
print("dim = " + str(t.dim()))
# 返回张量第一个维度的长度
print("size(0) = " + str(t.size(0)))
# 返回张量第二个维度的长度
print("size(1) = " + str(t.size(1)))
# 返回张量的元素个数
print("numel= " + str(t.numel()))


tensor([[0.7308, 0.3333, 0.5879, 0.1383],
        [0.6849, 0.7065, 0.8308, 0.2471],
        [0.9100, 0.7662, 0.2969, 0.7085]])
torch.float32
torch.Size([3, 4])
size = torch.Size([3, 4])
dim = 2
size(0) = 3
size(1) = 4
numel= 12


## 张量存储设备及其转移

In [17]:
# 返回张量的存储设备
print("device = " + str(t.device))
print("torch.cuda.is_available() = " + str(torch.cuda.is_available()))
# 将张量转移到GPU
if torch.cuda.is_available():
    t = t.to('cuda')
    print("device = " + str(t.device))

device = cpu
torch.cuda.is_available() = True
device = cuda:0


In [18]:
# 将张量转移到CPU
t = t.to('cpu')
print("device = " + str(t.device))

device = cpu


## 张量数据类型的转换

In [19]:
# 对张量进行数据类型转换
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)
print("----------------")
t = t.type(torch.float64)
print(t)
print(t.dtype)
print("----------------")
t = t.type(torch.int64)
print(t)
print(t.dtype)


tensor([1., 2., 3.])
torch.float32
----------------
tensor([1., 2., 3.], dtype=torch.float64)
torch.float64
----------------
tensor([1, 2, 3])
torch.int64


In [20]:
t = torch.randn(3, 4)
print(t)
print(t.dtype)
print("----------------")
# .long()方法可以将张量转换为64位整型，即int64，与t.type(torch.int64)等价
t = t.long()
print(t)
print(t.dtype)
print("----------------")
# .int()方法可以将张量转换为32位整型
# .short()方法可以将张量转换为16位整型
# .char()方法可以将张量转换为8位整型
# .byte()方法可以将张量转换为8位无符号整型

# .double()方法可以将张量转换为64位浮点型
# .float()方法可以将张量转换为32位浮点型
t = t.float()
print(t)
print(t.dtype)
print("----------------")
# .half()方法可以将张量转换为16位浮点型

# .bool()方法可以将张量转换为布尔型

tensor([[ 1.5564,  1.3932, -0.8936,  0.1820],
        [ 0.8170,  0.4725,  0.0844,  1.5326],
        [ 0.2691,  0.2472,  0.6079, -0.2840]])
torch.float32
----------------
tensor([[1, 1, 0, 0],
        [0, 0, 0, 1],
        [0, 0, 0, 0]])
torch.int64
----------------
tensor([[1., 1., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])
torch.float32
----------------


## 张量运算

In [21]:
# 加法：广播原则
t1 = torch.randn(3, 4)
print(t1)
# 数值与t1相加，每个元素加3
print(t1 + 3)
print("----------------")
# 与相同形状的张量相加,对应元素相加；与不同形状的张量相加，会报错
t2 = torch.randn(3, 4)
print(t2)
# print(t1 + t2)
# print(torch.add(t1, t2))
#等同于
print(t1.add(t2))   # t1的值不变
print("----------------")
print(t1)
print(t1.add_(t2))      # t1 = t1 + t2
# t1的值改变
print(t1)
print("----------------")
# 方法后面带下划线的方法会改变调用者的值
# 类似的方法还有sub（减法）、mul（乘法）、div（除法）、pow（幂运算）、sqrt（开方）
# log（对数运算）、exp（指数运算）、abs（绝对值）、neg（取负数）、reciprocal（取倒数）
# mean（求均值）、std（求标准差）、var（求方差）、norm（求范数）
# max（求最大值）、min（求最小值）、argmax（求最大值索引）、argmin（求最小值索引）
# sum（求和）、prod（求积）、cumsum（求累加和）、cumprod（求累乘积）
# round（四舍五入）、floor（向下取整）、ceil（向上取整）、trunc（取整数部分）、frac（取小数部分）等

tensor([[ 1.2872, -1.1640, -0.3579,  0.0377],
        [-1.0206, -0.8241, -0.6670, -1.1468],
        [ 0.4104,  0.0271, -2.1854,  0.3311]])
tensor([[4.2872, 1.8360, 2.6421, 3.0377],
        [1.9794, 2.1759, 2.3330, 1.8532],
        [3.4104, 3.0271, 0.8146, 3.3311]])
----------------
tensor([[-0.3058, -0.0689,  0.9351, -0.2130],
        [-0.2622, -0.6015,  0.7110, -0.2750],
        [-1.0764, -0.9532,  0.5018, -2.3148]])
tensor([[ 0.9815, -1.2329,  0.5772, -0.1753],
        [-1.2828, -1.4256,  0.0440, -1.4218],
        [-0.6659, -0.9261, -1.6836, -1.9836]])
----------------
tensor([[ 1.2872, -1.1640, -0.3579,  0.0377],
        [-1.0206, -0.8241, -0.6670, -1.1468],
        [ 0.4104,  0.0271, -2.1854,  0.3311]])
tensor([[ 0.9815, -1.2329,  0.5772, -0.1753],
        [-1.2828, -1.4256,  0.0440, -1.4218],
        [-0.6659, -0.9261, -1.6836, -1.9836]])
tensor([[ 0.9815, -1.2329,  0.5772, -0.1753],
        [-1.2828, -1.4256,  0.0440, -1.4218],
        [-0.6659, -0.9261, -1.6836, -1.9836]])
-----

In [ ]:
# matmul（矩阵乘法）、@（矩阵乘法）、T（转置）、transpose（转置）、permute（维度交换）、reshape（形状变换）、view（形状变换）
t1 = torch.randn(3, 4)
print(t1)
print(t1.T)
print(t1.matmul(t1.T))

tensor([[ 1.7365, -0.1485, -0.3830, -0.1339],
        [ 0.1765,  1.5365,  0.3226, -1.4356],
        [ 1.0029, -0.0522,  1.1279,  1.0141]])
tensor([[ 1.7365,  0.1765,  1.0029],
        [-0.1485,  1.5365, -0.0522],
        [-0.3830,  0.3226,  1.1279],
        [-0.1339, -1.4356,  1.0141]])
tensor([[ 3.2022,  0.1470,  1.1815],
        [ 0.1470,  4.5570, -0.9952],
        [ 1.1815, -0.9952,  3.3090]])


## 从张量转换为python和numpy的数据类型

In [ ]:
# 转换为Python数据类型
t2 = t1.sum()
print(t2)
print(t2.item())        # 将张量的值转换为Python数值
print(t1.tolist())      # 将张量的值转换为Python列表
result = t1.mean()      # 求均值
print(result)           # 返回一个张量
print(result.item())    # 返回一个Python数值

tensor(4.7637)
4.763683319091797
[[1.7365307807922363, -0.1484937220811844, -0.3830190598964691, -0.13388681411743164], [0.1764928102493286, 1.536466360092163, 0.32261475920677185, -1.4356259107589722], [1.0028729438781738, -0.05223654583096504, 1.1278895139694214, 1.014078140258789]]
tensor(0.3970)
0.3969736099243164


In [ ]:
# 转换为Numpy数据类型
# 从Numpy数组创建张量
np_array = np.random.randn(3, 4)
print(np_array)
t = torch.from_numpy(np_array)
print(t)
# 将张量转换为Numpy数组
# .numpy()方法可以将张量转换为Numpy数组
np_array = t.numpy()
print(np_array)


[[-0.41586645  0.03775906 -0.47233051  1.69069393]
 [-1.34760597  0.55274691 -0.94824349  0.21932203]
 [ 1.11510202  0.36372741  0.64968126  0.913406  ]]
tensor([[-0.4159,  0.0378, -0.4723,  1.6907],
        [-1.3476,  0.5527, -0.9482,  0.2193],
        [ 1.1151,  0.3637,  0.6497,  0.9134]], dtype=torch.float64)
[[-0.41586645  0.03775906 -0.47233051  1.69069393]
 [-1.34760597  0.55274691 -0.94824349  0.21932203]
 [ 1.11510202  0.36372741  0.64968126  0.913406  ]]


In [1]:
import torch

In [ ]:
x = torch.rand(2, 3)
print(x)

In [ ]:
x = torch.randn(2, 3)
print(x)

In [ ]:
x = torch.zeros(2, 3)
print(x)

In [ ]:
x = torch.ones(2, 3)
print(x)

In [ ]:
x.size()

In [ ]:
x.shape

In [ ]:
x = torch.tensor([6, 2])
print(x)

In [ ]:
x.size()

### 数据类型

In [ ]:
x = torch.tensor([6, 2], dtype=torch.float32)
print(x)

In [ ]:
x.type(torch.int64)

In [ ]:
x = torch.ones(2, 3, dtype=torch.float64)
print(x)

### 与ndarray数据类型的转换

In [52]:
import numpy as np

In [54]:
a = np.random.randn(2, 3)

In [ ]:
a

In [ ]:
x1 = torch.from_numpy(a)

In [ ]:
x1

In [ ]:
x1.numpy()

张量运算

In [ ]:
x + x1

In [ ]:
x

In [ ]:
x + 3

In [ ]:
x.add(x1)

In [ ]:
x.add_(x1)

In [ ]:
x

In [ ]:
x.view(3, 2) # x.reshape(3, 2)

In [ ]:
x.view(-1, 1) # x.reshape(-1, 1)

In [68]:
x = x.mean() # x.mean(dim=0)

In [ ]:
x

In [ ]:
x.item()

### 张量的自动微分

将Torch.Tensor属性 .requires_grad 设置为True，

pytorch将开始跟踪对此张量的所有操作。

完成计算后，可以调用 .backward() 并自动计算所有梯度。

该张量的梯度将累加到.grad属性中。

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

In [ ]:
x.requires_grad

In [111]:
x.grad

In [112]:
x.grad_fn   # 指向运算生成此张量的方法

In [ ]:
# 进行张量运算
y = x + 2
print(y)

In [ ]:
# y是由于运算而创建的，因此具有grad_fn属性

print(y.grad_fn)

In [ ]:
# 进行更多操作

z = y * y * 3
out = z.mean()

print(z, out)

### 计算梯度

In [116]:
out.backward()    # 自动微分运算, 注意 out 是标量值

打印梯度  d（out）/ dx   

out = f(x)

In [ ]:
print(x.grad)

In [ ]:
x.data

In [107]:
x.grad_fn

当张量的 requires_grad 属性为 True 时， 

pytorch会一直跟踪记录此张量的运算

当不需要跟踪计算时，可以通过将代码块包装在  with torch.no_grad(): 上下文中

In [ ]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

也可使用 .detach() 来获得具有相同内容但不需要跟踪运算的新Tensor ：

In [ ]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

In [ ]:
x.data

In [ ]:
x.detach()

使用 requires_grad_ 就地改变张量此属性

In [ ]:
a = torch.randn(2, 2)
a = a*3 + 2
print(a.requires_grad)

In [ ]:
a.requires_grad_(True)
print(a.requires_grad)

总结 pytorch 张量的数据结构形式