In [1]:
import torch

In [10]:
x = torch.rand(2, 3)
print(x)

tensor([[0.4701, 0.7980, 0.6190],
        [0.5790, 0.7073, 0.9331]])


In [11]:
x = torch.randn(2, 3)
print(x)

tensor([[ 1.9058, -0.9533, -0.8006],
        [ 1.5439, -0.1714,  0.1577]])


In [12]:
x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [14]:
x.size()

torch.Size([2, 3])

In [15]:
x.shape

torch.Size([2, 3])

In [8]:
x = torch.tensor([6, 2])
print(x)

tensor([6, 2])


In [9]:
x.size()

torch.Size([2])

### 数据类型

In [22]:
x = torch.tensor([6, 2], dtype=torch.float32)
print(x)

tensor([6., 2.])


In [23]:
x.type(torch.int64)

tensor([6, 2])

In [51]:
x = torch.ones(2, 3, dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


### 与ndarray数据类型的转换

In [52]:
import numpy as np

In [53]:
a = np.random.randn(2, 3)

In [54]:
a

array([[-0.4383083 ,  0.49690724, -1.9477965 ],
       [ 0.50349908, -0.49686913, -0.89424381]])

In [55]:
x1 = torch.from_numpy(a)

In [56]:
x1

tensor([[-0.4383,  0.4969, -1.9478],
        [ 0.5035, -0.4969, -0.8942]], dtype=torch.float64)

In [57]:
x1.numpy()

array([[-0.4383083 ,  0.49690724, -1.9477965 ],
       [ 0.50349908, -0.49686913, -0.89424381]])

张量运算

In [58]:
x + x1

tensor([[ 0.5617,  1.4969, -0.9478],
        [ 1.5035,  0.5031,  0.1058]], dtype=torch.float64)

In [59]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [60]:
x + 3

tensor([[4., 4., 4.],
        [4., 4., 4.]], dtype=torch.float64)

In [61]:
x.add(x1)

tensor([[ 0.5617,  1.4969, -0.9478],
        [ 1.5035,  0.5031,  0.1058]], dtype=torch.float64)

In [62]:
x.add_(x1)

tensor([[ 0.5617,  1.4969, -0.9478],
        [ 1.5035,  0.5031,  0.1058]], dtype=torch.float64)

In [63]:
x

tensor([[ 0.5617,  1.4969, -0.9478],
        [ 1.5035,  0.5031,  0.1058]], dtype=torch.float64)

In [64]:
x.view(3, 2)

tensor([[ 0.5617,  1.4969],
        [-0.9478,  1.5035],
        [ 0.5031,  0.1058]], dtype=torch.float64)

In [65]:
x.view(-1, 1)

tensor([[ 0.5617],
        [ 1.4969],
        [-0.9478],
        [ 1.5035],
        [ 0.5031],
        [ 0.1058]], dtype=torch.float64)

In [67]:
x = x.mean()

In [68]:
x

tensor(0.5372, dtype=torch.float64)

In [70]:
x.item()

0.5371980978235334

### 张量的自动微分

将Torch.Tensor属性 .requires_grad 设置为True，

pytorch将开始跟踪对此张量的所有操作。

完成计算后，可以调用 .backward() 并自动计算所有梯度。

该张量的梯度将累加到.grad属性中。

In [109]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [110]:
x.requires_grad

True

In [111]:
x.grad

In [112]:
x.grad_fn   # 指向运算生成此张量的方法

In [113]:
# 进行张量运算
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [114]:
# y是由于运算而创建的，因此具有grad_fn属性

print(y.grad_fn)

In [115]:
# 进行更多操作

z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


### 计算梯度

In [116]:
out.backward()    # 自动微分运算, 注意 out 是标量值

打印梯度  d（out）/ dx   

out = f(x)

In [105]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [106]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [107]:
x.grad_fn

当张量的 requires_grad 属性为 True 时， 

pytorch会一直跟踪记录此张量的运算

当不需要跟踪计算时，可以通过将代码块包装在  with torch.no_grad(): 上下文中

In [117]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


也可使用 .detach() 来获得具有相同内容但不需要跟踪运算的新Tensor ：

In [118]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

True
False


In [120]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [121]:
x.detach()

tensor([[1., 1.],
        [1., 1.]])

使用 requires_grad_ 就地改变张量此属性

In [125]:
a = torch.randn(2, 2)
a = a*3 + 2
print(a.requires_grad)

False


In [126]:
a.requires_grad_(True)
print(a.requires_grad)

True


总结 pytorch 张量的数据结构形式