# 张量和数据类型

In [12]:
import torch
import numpy as np

## 初始化张量

### 从Python列表初始化张量

In [13]:
t = torch.tensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


In [14]:
t = torch.tensor([1., 2., 3.])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [15]:
t = torch.FloatTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [16]:
t = torch.LongTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


### 从numpy的ndarray初始化

In [21]:
np_array = np.arange(12).reshape(3, 4)
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
t = torch.from_numpy(np_array)
# 也可以使用下面的方式
# t = torch.tensor(np_array)
print(t)
print(t.dtype)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)
torch.int32


## 张量（Tensor）基本数据类型

* 32位浮点型：torch.float32 / torch.float
* 64位浮点型：torch.float64
* 64位整型： torch.int64 / torch.long
* 32位整型： torch.int32
* 16位整型： torch.int16

In [32]:
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [33]:
t = torch.tensor([1, 2, 3], dtype=torch.float)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [34]:
t = torch.tensor([1, 2, 3], dtype=torch.long)
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


In [1]:
import torch

In [24]:
x = torch.rand(2, 3)
print(x)

tensor([[0.9581, 0.6547, 0.8526],
        [0.6734, 0.9931, 0.8090]])


In [25]:
x = torch.randn(2, 3)
print(x)

tensor([[ 0.0670,  0.2113, -0.0190],
        [ 0.1638, -0.1152,  0.9894]])


In [26]:
x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [27]:
x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [28]:
x.size()

torch.Size([2, 3])

In [29]:
x.shape

torch.Size([2, 3])

In [30]:
x = torch.tensor([6, 2])
print(x)

tensor([6, 2])


In [31]:
x.size()

torch.Size([2])

### 数据类型

In [35]:
x = torch.tensor([6, 2], dtype=torch.float32)
print(x)

tensor([6., 2.])


In [36]:
x.type(torch.int64)

tensor([6, 2])

In [37]:
x = torch.ones(2, 3, dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


### 与ndarray数据类型的转换

In [52]:
import numpy as np

In [53]:
a = np.random.randn(2, 3)

In [ ]:
a

In [55]:
x1 = torch.from_numpy(a)

In [ ]:
x1

In [ ]:
x1.numpy()

张量运算

In [ ]:
x + x1

In [ ]:
x

In [ ]:
x + 3

In [ ]:
x.add(x1)

In [ ]:
x.add_(x1)

In [ ]:
x

In [ ]:
x.view(3, 2)

In [ ]:
x.view(-1, 1)

In [67]:
x = x.mean()

In [ ]:
x

In [ ]:
x.item()

### 张量的自动微分

将Torch.Tensor属性 .requires_grad 设置为True，

pytorch将开始跟踪对此张量的所有操作。

完成计算后，可以调用 .backward() 并自动计算所有梯度。

该张量的梯度将累加到.grad属性中。

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

In [ ]:
x.requires_grad

In [111]:
x.grad

In [112]:
x.grad_fn   # 指向运算生成此张量的方法

In [ ]:
# 进行张量运算
y = x + 2
print(y)

In [ ]:
# y是由于运算而创建的，因此具有grad_fn属性

print(y.grad_fn)

In [ ]:
# 进行更多操作

z = y * y * 3
out = z.mean()

print(z, out)

### 计算梯度

In [116]:
out.backward()    # 自动微分运算, 注意 out 是标量值

打印梯度  d（out）/ dx   

out = f(x)

In [ ]:
print(x.grad)

In [ ]:
x.data

In [107]:
x.grad_fn

当张量的 requires_grad 属性为 True 时， 

pytorch会一直跟踪记录此张量的运算

当不需要跟踪计算时，可以通过将代码块包装在  with torch.no_grad(): 上下文中

In [ ]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

也可使用 .detach() 来获得具有相同内容但不需要跟踪运算的新Tensor ：

In [ ]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

In [ ]:
x.data

In [ ]:
x.detach()

使用 requires_grad_ 就地改变张量此属性

In [ ]:
a = torch.randn(2, 2)
a = a*3 + 2
print(a.requires_grad)

In [ ]:
a.requires_grad_(True)
print(a.requires_grad)

总结 pytorch 张量的数据结构形式