# 张量和数据类型

In [1]:
import torch
import numpy as np

## 初始化张量

### 从Python列表初始化张量

In [2]:
t = torch.tensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


In [3]:
t = torch.tensor([1., 2., 3.])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [4]:
t = torch.FloatTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [5]:
t = torch.LongTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


### 从numpy的ndarray初始化

In [6]:
np_array = np.arange(12).reshape(3, 4)
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
t = torch.from_numpy(np_array)
# 也可以使用下面的方式
# t = torch.tensor(np_array)
print(t)
print(t.dtype)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)
torch.int32


***

## 张量（Tensor）基本数据类型

* 32位浮点型：torch.float32 / torch.float
* 64位浮点型：torch.float64
* 64位整型： torch.int64 / torch.long
* 32位整型： torch.int32
* 16位整型： torch.int16

In [8]:
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [9]:
t = torch.tensor([1, 2, 3], dtype=torch.float)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [10]:
t = torch.tensor([1, 2, 3], dtype=torch.long)
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


***

## 创建随机值张量

In [11]:
# 创建（0，1）之间均匀分布的随机数
t = torch.rand(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[0.2842, 0.3396, 0.6993, 0.1519],
        [0.9724, 0.8568, 0.2587, 0.1435],
        [0.1248, 0.6224, 0.6081, 0.9475]])
torch.float32
torch.Size([3, 4])


In [12]:
# 创建标准正态分布的随机数
t = torch.randn(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[ 0.9144,  1.2348,  0.9430,  0.3681],
        [ 1.1816, -0.9288, -0.7011, -0.7610],
        [ 0.9570,  0.5369,  1.4253, -1.7843]])
torch.float32
torch.Size([3, 4])


In [13]:
# 创建全0的张量
t = torch.zeros(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
torch.Size([3, 4])


In [14]:
# 创建全1的张量
t = torch.ones(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.Size([3, 4])


In [15]:
# 创建一个与t形状相同的张量，但是值是正态分布的随机数
t = torch.randn_like(t)
print(t)
print(t.dtype)
print(t.shape)

tensor([[ 0.6723, -0.5992,  0.8991,  1.6448],
        [ 1.1502, -0.6241,  0.5018, -0.2875],
        [ 0.2762,  1.1672, -0.3976,  2.4684]])
torch.float32
torch.Size([3, 4])


***

## 张量的属性

In [16]:
# 创建一个与t形状相同的张量，但是值是在（0，1）均匀分布的随机数
t = torch.rand_like(t)
print(t)
# 返回张量的数据类型
print(t.dtype)
# 返回张量的形状
print(t.shape)
print("size = " + str(t.size()))
# 返回张量的维度
print("dim = " + str(t.dim()))
# 返回张量第一个维度的长度
print("size(0) = " + str(t.size(0)))
# 返回张量第二个维度的长度
print("size(1) = " + str(t.size(1)))
# 返回张量的元素个数
print("numel= " + str(t.numel()))


tensor([[0.8124, 0.0219, 0.2118, 0.8947],
        [0.8083, 0.0802, 0.4819, 0.0896],
        [0.7054, 0.5777, 0.1773, 0.6074]])
torch.float32
torch.Size([3, 4])
size = torch.Size([3, 4])
dim = 2
size(0) = 3
size(1) = 4
numel= 12


***

## 张量存储设备及其转移

In [17]:
# 返回张量的存储设备
print("device = " + str(t.device))
print("torch.cuda.is_available() = " + str(torch.cuda.is_available()))
# 将张量转移到GPU
if torch.cuda.is_available():
    t = t.to('cuda')
    print("device = " + str(t.device))

device = cpu
torch.cuda.is_available() = True
device = cuda:0


In [18]:
# 将张量转移到CPU
t = t.to('cpu')
print("device = " + str(t.device))

device = cpu


***

## 张量数据类型的转换

In [19]:
# 对张量进行数据类型转换
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)
print("----------------")
t = t.type(torch.float64)
print(t)
print(t.dtype)
print("----------------")
t = t.type(torch.int64)
print(t)
print(t.dtype)


tensor([1., 2., 3.])
torch.float32
----------------
tensor([1., 2., 3.], dtype=torch.float64)
torch.float64
----------------
tensor([1, 2, 3])
torch.int64


In [20]:
t = torch.randn(3, 4)
print(t)
print(t.dtype)
print("----------------")
# .long()方法可以将张量转换为64位整型，即int64，与t.type(torch.int64)等价
t = t.long()
print(t)
print(t.dtype)
print("----------------")
# .int()方法可以将张量转换为32位整型
# .short()方法可以将张量转换为16位整型
# .char()方法可以将张量转换为8位整型
# .byte()方法可以将张量转换为8位无符号整型

# .double()方法可以将张量转换为64位浮点型
# .float()方法可以将张量转换为32位浮点型
t = t.float()
print(t)
print(t.dtype)
print("----------------")
# .half()方法可以将张量转换为16位浮点型

# .bool()方法可以将张量转换为布尔型

tensor([[-0.2655, -0.3575,  0.8830,  0.0955],
        [ 0.1939, -0.5710,  1.3606, -0.2213],
        [ 1.1910,  0.2361, -0.4279,  0.5251]])
torch.float32
----------------
tensor([[0, 0, 0, 0],
        [0, 0, 1, 0],
        [1, 0, 0, 0]])
torch.int64
----------------
tensor([[0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [1., 0., 0., 0.]])
torch.float32
----------------


***

## 张量运算

In [21]:
# 加法：广播原则
t1 = torch.randn(3, 4)
print(t1)
# 数值与t1相加，每个元素加3
print(t1 + 3)
print("----------------")
# 与相同形状的张量相加,对应元素相加；与不同形状的张量相加，会报错
t2 = torch.randn(3, 4)
print(t2)
# print(t1 + t2)
# print(torch.add(t1, t2))
#等同于
print(t1.add(t2))   # t1的值不变
print("----------------")
print(t1)
print(t1.add_(t2))      # t1 = t1 + t2
# t1的值改变
print(t1)
print("----------------")
# 方法后面带下划线的方法会改变调用者的值
# 类似的方法还有sub（减法）、mul（乘法）、div（除法）、pow（幂运算）、sqrt（开方）
# log（对数运算）、exp（指数运算）、abs（绝对值）、neg（取负数）、reciprocal（取倒数）
# mean（求均值）、std（求标准差）、var（求方差）、norm（求范数）
# max（求最大值）、min（求最小值）、argmax（求最大值索引）、argmin（求最小值索引）
# sum（求和）、prod（求积）、cumsum（求累加和）、cumprod（求累乘积）
# round（四舍五入）、floor（向下取整）、ceil（向上取整）、trunc（取整数部分）、frac（取小数部分）等

tensor([[ 1.2043, -0.6727,  0.8901,  0.1895],
        [ 0.0866, -0.2690,  1.1998,  0.2302],
        [-0.0633,  0.0155, -0.9118, -1.3493]])
tensor([[4.2043, 2.3273, 3.8901, 3.1895],
        [3.0866, 2.7310, 4.1998, 3.2302],
        [2.9367, 3.0155, 2.0882, 1.6507]])
----------------
tensor([[-1.4831, -0.1382,  1.2668,  1.2941],
        [ 1.2917, -0.8616,  0.5389, -0.6363],
        [ 0.8621, -0.4392,  0.5837, -0.0272]])
tensor([[-0.2787, -0.8109,  2.1568,  1.4836],
        [ 1.3783, -1.1307,  1.7387, -0.4061],
        [ 0.7988, -0.4237, -0.3281, -1.3765]])
----------------
tensor([[ 1.2043, -0.6727,  0.8901,  0.1895],
        [ 0.0866, -0.2690,  1.1998,  0.2302],
        [-0.0633,  0.0155, -0.9118, -1.3493]])
tensor([[-0.2787, -0.8109,  2.1568,  1.4836],
        [ 1.3783, -1.1307,  1.7387, -0.4061],
        [ 0.7988, -0.4237, -0.3281, -1.3765]])
tensor([[-0.2787, -0.8109,  2.1568,  1.4836],
        [ 1.3783, -1.1307,  1.7387, -0.4061],
        [ 0.7988, -0.4237, -0.3281, -1.3765]])
-----

In [22]:
# matmul（矩阵乘法）、@（矩阵乘法）、T（转置）、transpose（转置）、permute（维度交换）、reshape（形状变换）、view（形状变换）
t1 = torch.randn(3, 4)
print(t1)
print(t1.T)
print(t1.matmul(t1.T))

tensor([[-0.1099,  1.5865, -0.0832, -0.9344],
        [-1.1482,  0.0420, -0.5706, -0.1047],
        [-0.7832, -1.3121, -0.5980, -0.1246]])
tensor([[-0.1099, -1.1482, -0.7832],
        [ 1.5865,  0.0420, -1.3121],
        [-0.0832, -0.5706, -0.5980],
        [-0.9344, -0.1047, -0.1246]])
tensor([[ 3.4090,  0.3380, -1.8293],
        [ 0.3380,  1.6566,  1.1985],
        [-1.8293,  1.1985,  2.7080]])


***

## 从张量转换为python和numpy的数据类型

In [23]:
# 转换为Python数据类型
t2 = t1.sum()
print(t2)
print(t2.item())        # 将张量的值转换为Python数值
print(t1.tolist())      # 将张量的值转换为Python列表
result = t1.mean()      # 求均值
print(result)           # 返回一个张量
print(result.item())    # 返回一个Python数值

tensor(-4.1404)
-4.140439987182617
[[-0.10986185073852539, 1.5864835977554321, -0.08321221172809601, -0.9343912601470947], [-1.148163914680481, 0.04196036979556084, -0.570621132850647, -0.10472740978002548], [-0.7831873297691345, -1.3120564222335815, -0.5980182886123657, -0.12464436888694763]]
tensor(-0.3450)
-0.34503665566444397


In [24]:
# 转换为Numpy数据类型
# 从Numpy数组创建张量
np_array = np.random.randn(3, 4)
print(np_array)
t = torch.from_numpy(np_array)
print(t)
# 将张量转换为Numpy数组
# .numpy()方法可以将张量转换为Numpy数组
np_array = t.numpy()
print(np_array)


[[-1.77654325  0.91412871 -0.08365033  0.68929413]
 [-0.22986805 -0.21233439 -1.42526056  1.33462006]
 [-0.19253394  0.20843638  0.23951911 -0.23536488]]
tensor([[-1.7765,  0.9141, -0.0837,  0.6893],
        [-0.2299, -0.2123, -1.4253,  1.3346],
        [-0.1925,  0.2084,  0.2395, -0.2354]], dtype=torch.float64)
[[-1.77654325  0.91412871 -0.08365033  0.68929413]
 [-0.22986805 -0.21233439 -1.42526056  1.33462006]
 [-0.19253394  0.20843638  0.23951911 -0.23536488]]


***

## 张量的变形

In [25]:
t = torch.randn(3, 4)
print(t)
print(t.shape)
# .view()方法可以改变张量的形状，但是张量的元素个数不能改变
t1 = t.view(4, 3)
print(t1)
print(t1.shape)
# .reshape()方法与.view()方法功能相同

tensor([[ 0.9548,  1.0537, -1.3611, -0.0043],
        [-1.7687,  0.6500,  2.1519,  0.3830],
        [-0.4163,  0.9507, -1.1007,  3.2486]])
torch.Size([3, 4])
tensor([[ 0.9548,  1.0537, -1.3611],
        [-0.0043, -1.7687,  0.6500],
        [ 2.1519,  0.3830, -0.4163],
        [ 0.9507, -1.1007,  3.2486]])
torch.Size([4, 3])


In [26]:
# 常用于展平张量
t = torch.randn(3, 4)
print(t)
print(t.shape)
# 转换为第二维度为1的张量，-1表示自动计算
t1 = t.view(-1, 1)  #即将t展平为 24 * 1 的张量
print(t1)
print(t1.shape)
# 例如
t = torch.randn(12, 3, 4, 4)
print(t.shape)
# 将t展平为 12 * 48 的张量
t1 = t.view(12, -1)
# 也可写为
t1 = t.view(12, 48)  # 12 * 3 * 4 * 4 = 12 * 48
print(t1.shape)

tensor([[-0.7189, -0.9602, -0.9092,  0.2134],
        [ 0.2214,  1.3995, -0.0514,  0.5768],
        [-0.8315,  0.7172, -0.7900, -0.9001]])
torch.Size([3, 4])
tensor([[-0.7189],
        [-0.9602],
        [-0.9092],
        [ 0.2134],
        [ 0.2214],
        [ 1.3995],
        [-0.0514],
        [ 0.5768],
        [-0.8315],
        [ 0.7172],
        [-0.7900],
        [-0.9001]])
torch.Size([12, 1])
torch.Size([12, 3, 4, 4])
torch.Size([12, 48])


In [27]:
# 给张量增加一个维度，例如将形状为(3, 4)的张量增加一个维度，形状变为(1, 3, 4)
t = torch.randn(3, 4)
print(t)
print(t.shape)
# .unsqueeze()方法可以增加张量为1的维度
t1 = t.unsqueeze(0) # 在第0维度增加一个维度
print(t1)
print(t1.shape)
# 也可以写为
# t1 = t.view(1, 3, 4)
# print(t1)
# print(t1.shape)

# 给张量减少一个维度
# .squeeze()方法可以减少张量为1的维度
t2 = t1.squeeze()
print(t2)
print(t2.shape)

tensor([[-0.2284,  0.8852,  0.7281,  0.4910],
        [-0.8244,  1.5591,  0.9337,  0.2384],
        [ 1.7139,  0.3170,  0.2344, -0.1537]])
torch.Size([3, 4])
tensor([[[-0.2284,  0.8852,  0.7281,  0.4910],
         [-0.8244,  1.5591,  0.9337,  0.2384],
         [ 1.7139,  0.3170,  0.2344, -0.1537]]])
torch.Size([1, 3, 4])
tensor([[-0.2284,  0.8852,  0.7281,  0.4910],
        [-0.8244,  1.5591,  0.9337,  0.2384],
        [ 1.7139,  0.3170,  0.2344, -0.1537]])
torch.Size([3, 4])


***

## 张量的自动微分

In [28]:
t = torch.randn(3, 4)
print(t.requires_grad) # tensor的requires_grad属性默认为False， 表示不需要Pytorch自动跟踪
t.requires_grad = True # 设置requires_grad属性为True，Pytorch将开始跟踪对此张量的所有操作
print(t.requires_grad) 

False
True


1. 将`Torch.Tensor`属性`.requires_grad`设置为`True`，Pytorch将开始跟踪对此张量的所有操作。

2. 完成计算后，可以调用`.backward()`并自动计算所有梯度，该张量的梯度将累加到`.grad`属性中。

In [29]:
t = torch.ones(3, 4, requires_grad=True) # 创建一个requires_grad属性为True的张量
print(t)
print(t.requires_grad)
x = t + 5
print(x)
print(x.grad_fn)        # grad_fn属性表示张量的创建方式，x是通过加法操作创建的
print(x.requires_grad)  # x会继承t的requires_grad属性
y = x * 2
print(y)
print(y.grad_fn)        # y是通过乘法操作创建的
print(y.requires_grad)  # y会继承x的requires_grad属性
z = y.mean()            # 求y的均值, z是一个标量值，维度为0
print(z)
print(z.grad_fn)        # z是通过mean操作创建的
print(z.requires_grad)  # z会继承y的requires_grad属性
z.backward()        # 反向传播，自动微分运算，计算梯度
print(t.grad)       # t.grad属性保存了t的梯度，dz/dt = 1/12
print(t.grad_fn)    # t.grad_fn属性为None，因为t是用户创建的张量，不是通过操作创建的
print(z.grad_fn)    # z.grad_fn属性为MeanBackward0，表示z是通过mean操作创建的


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)
True
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]], grad_fn=<AddBackward0>)
True
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]], grad_fn=<MulBackward0>)
True
tensor(12., grad_fn=<MeanBackward0>)
True
tensor([[0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667]])
None


### 处理不需要跟踪计算的操作

* 当张量的`requires_grad`属性为`True`时，Pytorch会一直跟踪记录此张量的运算
* 当不需要跟踪计算时，可以通过将代码块包装在`with torch.no_grad():`上下文中

In [30]:
t = torch.ones(3, 4, requires_grad=True)
# 使用torch.no_grad()上下文管理器，可以临时关闭自动微分
with torch.no_grad():
    x = t + 5
    print(x.requires_grad)  # x则不会继承t的requires_grad属性
y = t * 2
print(y.requires_grad)  # y会继承t的requires_grad属性

# 或者设置requires_grad属性为False，直接关闭自动微分
t.requires_grad_(False) # 设置t的requires_grad属性为False
z = t.mean()
print(z.requires_grad)  # y的requires_grad属性为False

# 使用detach()方法，可以将张量从计算图中分离，不再跟踪
t = torch.ones(3, 4, requires_grad=True)
x = t.detach()
print(x.requires_grad)  # x的requires_grad属性为False

False
True
False
False


***