# 张量和数据类型

In [2]:
import torch
import numpy as np

## 初始化张量

### 从Python列表初始化张量

In [3]:
t = torch.tensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


In [4]:
t = torch.tensor([1., 2., 3.])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [5]:
t = torch.FloatTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [6]:
t = torch.LongTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


### 从numpy的ndarray初始化

In [7]:
np_array = np.arange(12).reshape(3, 4)
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
t = torch.from_numpy(np_array)
# 也可以使用下面的方式
# t = torch.tensor(np_array)
print(t)
print(t.dtype)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)
torch.int32


## 张量（Tensor）基本数据类型

* 32位浮点型：torch.float32 / torch.float
* 64位浮点型：torch.float64
* 64位整型： torch.int64 / torch.long
* 32位整型： torch.int32
* 16位整型： torch.int16

In [9]:
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [10]:
t = torch.tensor([1, 2, 3], dtype=torch.float)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [11]:
t = torch.tensor([1, 2, 3], dtype=torch.long)
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


## 创建随机值张量

In [12]:
# 创建（0，1）之间均匀分布的随机数
t = torch.rand(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[3.3105e-01, 5.7900e-01, 6.5820e-01, 5.4869e-01],
        [8.3923e-04, 8.7101e-01, 7.1390e-01, 9.6161e-01],
        [8.8032e-01, 4.8163e-02, 1.0496e-01, 8.4463e-01]])
torch.float32
torch.Size([3, 4])


In [13]:
# 创建标准正态分布的随机数
t = torch.randn(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[-0.7259, -0.1204, -1.7273, -0.3712],
        [-0.5533, -0.0228,  1.0727, -1.1299],
        [ 0.8597, -1.6165, -0.6357,  0.6271]])
torch.float32
torch.Size([3, 4])


In [14]:
# 创建全0的张量
t = torch.zeros(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
torch.Size([3, 4])


In [15]:
# 创建全1的张量
t = torch.ones(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.Size([3, 4])


In [16]:
# 创建一个与t形状相同的张量，但是值是正态分布的随机数
t = torch.randn_like(t)
print(t)
print(t.dtype)
print(t.shape)

tensor([[-0.4475, -0.2987, -1.1818, -0.8400],
        [ 1.9000, -0.4951,  0.7524, -0.7127],
        [ 1.7838, -0.8828,  0.4194, -0.6119]])
torch.float32
torch.Size([3, 4])


## 张量的属性

In [17]:
# 创建一个与t形状相同的张量，但是值是在（0，1）均匀分布的随机数
t = torch.rand_like(t)
print(t)
# 返回张量的数据类型
print(t.dtype)
# 返回张量的形状
print(t.shape)
print("size = " + str(t.size()))
# 返回张量的维度
print("dim = " + str(t.dim()))
# 返回张量第一个维度的长度
print("size(0) = " + str(t.size(0)))
# 返回张量第二个维度的长度
print("size(1) = " + str(t.size(1)))
# 返回张量的元素个数
print("numel= " + str(t.numel()))


tensor([[0.7601, 0.8023, 0.8020, 0.1646],
        [0.8516, 0.5505, 0.6478, 0.9243],
        [0.7059, 0.2616, 0.3295, 0.9709]])
torch.float32
torch.Size([3, 4])
size = torch.Size([3, 4])
dim = 2
size(0) = 3
size(1) = 4
numel= 12


## 张量存储设备及其转移

In [18]:
# 返回张量的存储设备
print("device = " + str(t.device))
print("torch.cuda.is_available() = " + str(torch.cuda.is_available()))
# 将张量转移到GPU
if torch.cuda.is_available():
    t = t.to('cuda')
    print("device = " + str(t.device))

device = cpu
torch.cuda.is_available() = True
device = cuda:0


In [19]:
# 将张量转移到CPU
t = t.to('cpu')
print("device = " + str(t.device))

device = cpu


## 张量数据类型的转换

In [20]:
# 对张量进行数据类型转换
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)
print("----------------")
t = t.type(torch.float64)
print(t)
print(t.dtype)
print("----------------")
t = t.type(torch.int64)
print(t)
print(t.dtype)


tensor([1., 2., 3.])
torch.float32
----------------
tensor([1., 2., 3.], dtype=torch.float64)
torch.float64
----------------
tensor([1, 2, 3])
torch.int64


In [21]:
t = torch.randn(3, 4)
print(t)
print(t.dtype)
print("----------------")
# .long()方法可以将张量转换为64位整型，即int64，与t.type(torch.int64)等价
t = t.long()
print(t)
print(t.dtype)
print("----------------")
# .int()方法可以将张量转换为32位整型
# .short()方法可以将张量转换为16位整型
# .char()方法可以将张量转换为8位整型
# .byte()方法可以将张量转换为8位无符号整型

# .double()方法可以将张量转换为64位浮点型
# .float()方法可以将张量转换为32位浮点型
t = t.float()
print(t)
print(t.dtype)
print("----------------")
# .half()方法可以将张量转换为16位浮点型

# .bool()方法可以将张量转换为布尔型

tensor([[ 0.3276, -0.7074, -0.9388,  1.3879],
        [ 0.8291,  1.0274,  1.9375,  0.5639],
        [ 0.4855, -0.9693, -1.3564,  0.2914]])
torch.float32
----------------
tensor([[ 0,  0,  0,  1],
        [ 0,  1,  1,  0],
        [ 0,  0, -1,  0]])
torch.int64
----------------
tensor([[ 0.,  0.,  0.,  1.],
        [ 0.,  1.,  1.,  0.],
        [ 0.,  0., -1.,  0.]])
torch.float32
----------------


## 张量运算

In [22]:
# 加法：广播原则
t1 = torch.randn(3, 4)
print(t1)
# 数值与t1相加，每个元素加3
print(t1 + 3)
print("----------------")
# 与相同形状的张量相加,对应元素相加；与不同形状的张量相加，会报错
t2 = torch.randn(3, 4)
print(t2)
# print(t1 + t2)
# print(torch.add(t1, t2))
#等同于
print(t1.add(t2))   # t1的值不变
print("----------------")
print(t1)
print(t1.add_(t2))      # t1 = t1 + t2
# t1的值改变
print(t1)
print("----------------")
# 方法后面带下划线的方法会改变调用者的值
# 类似的方法还有sub（减法）、mul（乘法）、div（除法）、pow（幂运算）、sqrt（开方）
# log（对数运算）、exp（指数运算）、abs（绝对值）、neg（取负数）、reciprocal（取倒数）
# mean（求均值）、std（求标准差）、var（求方差）、norm（求范数）
# max（求最大值）、min（求最小值）、argmax（求最大值索引）、argmin（求最小值索引）
# sum（求和）、prod（求积）、cumsum（求累加和）、cumprod（求累乘积）
# round（四舍五入）、floor（向下取整）、ceil（向上取整）、trunc（取整数部分）、frac（取小数部分）等

tensor([[ 0.6854,  1.2489,  2.0136,  1.3021],
        [ 0.0060, -0.0854,  0.3379, -0.5216],
        [ 0.5676, -0.0357,  0.9664, -1.6810]])
tensor([[3.6854, 4.2489, 5.0136, 4.3021],
        [3.0060, 2.9146, 3.3379, 2.4784],
        [3.5676, 2.9643, 3.9664, 1.3190]])
----------------
tensor([[ 1.3979e+00,  4.0749e-01, -5.2264e-01,  1.4389e+00],
        [-6.2534e-01, -1.3638e+00, -4.0378e-01, -1.2230e-03],
        [-4.9570e-01, -1.1387e+00, -8.1026e-01, -8.6842e-01]])
tensor([[ 2.0833,  1.6564,  1.4910,  2.7409],
        [-0.6193, -1.4492, -0.0659, -0.5228],
        [ 0.0719, -1.1744,  0.1561, -2.5494]])
----------------
tensor([[ 0.6854,  1.2489,  2.0136,  1.3021],
        [ 0.0060, -0.0854,  0.3379, -0.5216],
        [ 0.5676, -0.0357,  0.9664, -1.6810]])
tensor([[ 2.0833,  1.6564,  1.4910,  2.7409],
        [-0.6193, -1.4492, -0.0659, -0.5228],
        [ 0.0719, -1.1744,  0.1561, -2.5494]])
tensor([[ 2.0833,  1.6564,  1.4910,  2.7409],
        [-0.6193, -1.4492, -0.0659, -0.5228],
    

In [23]:
# matmul（矩阵乘法）、@（矩阵乘法）、T（转置）、transpose（转置）、permute（维度交换）、reshape（形状变换）、view（形状变换）
t1 = torch.randn(3, 4)
print(t1)
print(t1.T)
print(t1.matmul(t1.T))

tensor([[-0.7738,  0.0293,  2.3433,  0.7309],
        [-0.9859, -0.5392,  0.9034,  1.0816],
        [ 0.6468, -0.3874,  0.6935, -1.3035]])
tensor([[-0.7738, -0.9859,  0.6468],
        [ 0.0293, -0.5392, -0.3874],
        [ 2.3433,  0.9034,  0.6935],
        [ 0.7309,  1.0816, -1.3035]])
tensor([[ 6.6251,  3.6547,  0.1606],
        [ 3.6547,  3.2487, -1.2121],
        [ 0.1606, -1.2121,  2.7486]])


## 从张量转换为python和numpy的数据类型

In [24]:
# 转换为Python数据类型
t2 = t1.sum()
print(t2)
print(t2.item())        # 将张量的值转换为Python数值
print(t1.tolist())      # 将张量的值转换为Python列表
result = t1.mean()      # 求均值
print(result)           # 返回一个张量
print(result.item())    # 返回一个Python数值

tensor(2.4390)
2.4389853477478027
[[-0.7738298177719116, 0.029250146821141243, 2.34333872795105, 0.730888843536377], [-0.9859098792076111, -0.5391919016838074, 0.9034125208854675, 1.0815544128417969], [0.6468090415000916, -0.38736653327941895, 0.6935497522354126, -1.30351984500885]]
tensor(0.2032)
0.2032487839460373


In [25]:
# 转换为Numpy数据类型
# 从Numpy数组创建张量
np_array = np.random.randn(3, 4)
print(np_array)
t = torch.from_numpy(np_array)
print(t)
# 将张量转换为Numpy数组
# .numpy()方法可以将张量转换为Numpy数组
np_array = t.numpy()
print(np_array)


[[ 1.18423523  0.2040645   0.71792539 -0.87057302]
 [ 0.60033821 -0.21742214 -0.95880386  0.57666865]
 [-0.17555106  0.67286956  0.0283364   0.10643364]]
tensor([[ 1.1842,  0.2041,  0.7179, -0.8706],
        [ 0.6003, -0.2174, -0.9588,  0.5767],
        [-0.1756,  0.6729,  0.0283,  0.1064]], dtype=torch.float64)
[[ 1.18423523  0.2040645   0.71792539 -0.87057302]
 [ 0.60033821 -0.21742214 -0.95880386  0.57666865]
 [-0.17555106  0.67286956  0.0283364   0.10643364]]


## 张量的变形

In [26]:
t = torch.randn(3, 4)
print(t)
print(t.shape)
# .view()方法可以改变张量的形状，但是张量的元素个数不能改变
t1 = t.view(4, 3)
print(t1)
print(t1.shape)
# .reshape()方法与.view()方法功能相同

tensor([[-0.7868,  3.2331,  0.7091, -1.0217],
        [ 0.6799,  0.6114, -0.9859, -0.2480],
        [ 0.0792,  1.5393,  0.9303, -0.1081]])
torch.Size([3, 4])
tensor([[-0.7868,  3.2331,  0.7091],
        [-1.0217,  0.6799,  0.6114],
        [-0.9859, -0.2480,  0.0792],
        [ 1.5393,  0.9303, -0.1081]])
torch.Size([4, 3])


In [27]:
# 常用于展平张量
t = torch.randn(3, 4)
print(t)
print(t.shape)
# 转换为第二维度为1的张量，-1表示自动计算
t1 = t.view(-1, 1)  #即将t展平为 24 * 1 的张量
print(t1)
print(t1.shape)
# 例如
t = torch.randn(12, 3, 4, 4)
print(t.shape)
# 将t展平为 12 * 48 的张量
t1 = t.view(12, -1)
# 也可写为
t1 = t.view(12, 48)  # 12 * 3 * 4 * 4 = 12 * 48
print(t1.shape)

tensor([[-0.5386,  0.9959, -0.3789,  1.1488],
        [-0.8533, -1.4846, -0.7018,  0.7646],
        [-0.6415,  0.3162,  0.2997, -0.8204]])
torch.Size([3, 4])
tensor([[-0.5386],
        [ 0.9959],
        [-0.3789],
        [ 1.1488],
        [-0.8533],
        [-1.4846],
        [-0.7018],
        [ 0.7646],
        [-0.6415],
        [ 0.3162],
        [ 0.2997],
        [-0.8204]])
torch.Size([12, 1])
torch.Size([12, 3, 4, 4])
torch.Size([12, 48])


In [28]:
# 给张量增加一个维度，例如将形状为(3, 4)的张量增加一个维度，形状变为(1, 3, 4)
t = torch.randn(3, 4)
print(t)
print(t.shape)
# .unsqueeze()方法可以增加张量为1的维度
t1 = t.unsqueeze(0) # 在第0维度增加一个维度
print(t1)
print(t1.shape)
# 也可以写为
# t1 = t.view(1, 3, 4)
# print(t1)
# print(t1.shape)

# 给张量减少一个维度
# .squeeze()方法可以减少张量为1的维度
t2 = t1.squeeze()
print(t2)
print(t2.shape)

tensor([[ 0.3957,  0.8839, -0.1224,  0.6148],
        [-1.4185, -1.4787,  1.1800,  2.1371],
        [ 0.9390,  0.1178, -0.5285, -0.8593]])
torch.Size([3, 4])
tensor([[[ 0.3957,  0.8839, -0.1224,  0.6148],
         [-1.4185, -1.4787,  1.1800,  2.1371],
         [ 0.9390,  0.1178, -0.5285, -0.8593]]])
torch.Size([1, 3, 4])
tensor([[ 0.3957,  0.8839, -0.1224,  0.6148],
        [-1.4185, -1.4787,  1.1800,  2.1371],
        [ 0.9390,  0.1178, -0.5285, -0.8593]])
torch.Size([3, 4])


## 张量的自动微分

In [29]:
t = torch.randn(3, 4)
print(t.requires_grad) # tensor的requires_grad属性默认为False， 表示不需要Pytorch自动跟踪
t.requires_grad = True # 设置requires_grad属性为True，Pytorch将开始跟踪对此张量的所有操作
print(t.requires_grad) 

False
True


1. 将`Torch.Tensor`属性`.requires_grad`设置为`True`，Pytorch将开始跟踪对此张量的所有操作。

2. 完成计算后，可以调用`.backward()`并自动计算所有梯度，该张量的梯度将累加到`.grad`属性中。

In [30]:
t = torch.ones(3, 4, requires_grad=True) # 创建一个requires_grad属性为True的张量
print(t)
print(t.requires_grad)
x = t + 5
print(x)
print(x.grad_fn)        # grad_fn属性表示张量的创建方式，x是通过加法操作创建的
print(x.requires_grad)  # x会继承t的requires_grad属性
y = x * 2
print(y)
print(y.grad_fn)        # y是通过乘法操作创建的
print(y.requires_grad)  # y会继承x的requires_grad属性
z = y.mean()            # 求y的均值, z是一个标量值，维度为0
print(z)
print(z.grad_fn)        # z是通过mean操作创建的
print(z.requires_grad)  # z会继承y的requires_grad属性
z.backward()        # 反向传播，自动微分运算，计算梯度
print(t.grad)       # t.grad属性保存了t的梯度，dz/dt = 1/12
print(t.grad_fn)    # t.grad_fn属性为None，因为t是用户创建的张量，不是通过操作创建的
print(z.grad_fn)    # z.grad_fn属性为MeanBackward0，表示z是通过mean操作创建的


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)
True
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]], grad_fn=<AddBackward0>)
True
tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [12., 12., 12., 12.]], grad_fn=<MulBackward0>)
True
tensor(12., grad_fn=<MeanBackward0>)
True
tensor([[0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667, 0.1667]])
None


### 处理不需要跟踪计算的操作

* 当张量的`requires_grad`属性为`True`时，Pytorch会一直跟踪记录此张量的运算
* 当不需要跟踪计算时，可以通过将代码块包装在`with torch.no_grad():`上下文中

In [69]:
t = torch.ones(3, 4, requires_grad=True)
# 使用torch.no_grad()上下文管理器，可以临时关闭自动微分
with torch.no_grad():
    x = t + 5
    print(x.requires_grad)  # x则不会继承t的requires_grad属性
y = t * 2
print(y.requires_grad)  # y会继承t的requires_grad属性

# 或者设置requires_grad属性为False，直接关闭自动微分
t.requires_grad_(False) # 设置t的requires_grad属性为False
z = t.mean()
print(z.requires_grad)  # y的requires_grad属性为False

# 使用detach()方法，可以将张量从计算图中分离，不再跟踪
t = torch.ones(3, 4, requires_grad=True)
x = t.detach()
print(x.requires_grad)  # x的requires_grad属性为False

False
True
False
False


### 张量的自动微分

将Torch.Tensor属性 .requires_grad 设置为True，

pytorch将开始跟踪对此张量的所有操作。

完成计算后，可以调用 .backward() 并自动计算所有梯度。

该张量的梯度将累加到.grad属性中。

In [34]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [35]:
x.requires_grad

True

In [36]:
x.grad

In [37]:
x.grad_fn   # 指向运算生成此张量的方法

In [38]:
# 进行张量运算
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [39]:
# y是由于运算而创建的，因此具有grad_fn属性

print(y.grad_fn)

In [40]:
# 进行更多操作

z = y * 2
out = z.mean()

print(z, out)

tensor([[6., 6.],
        [6., 6.]], grad_fn=<MulBackward0>) tensor(6., grad_fn=<MeanBackward0>)


### 计算梯度

In [41]:
out.backward()    # 自动微分运算, 注意 out 是标量值

打印梯度  d（out）/ dx   

out = f(x)

In [42]:
print(x.grad)

tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])


In [43]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [44]:
x.grad_fn

当张量的 requires_grad 属性为 True 时， 

pytorch会一直跟踪记录此张量的运算

当不需要跟踪计算时，可以通过将代码块包装在  with torch.no_grad(): 上下文中

In [45]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


也可使用 .detach() 来获得具有相同内容但不需要跟踪运算的新Tensor ：

In [46]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

True
False


In [47]:
x.data

tensor([[1., 1.],
        [1., 1.]])

In [48]:
x.detach()

tensor([[1., 1.],
        [1., 1.]])

使用 requires_grad_ 就地改变张量此属性

In [49]:
a = torch.randn(2, 2)
a = a*3 + 2
print(a.requires_grad)

False


In [50]:
a.requires_grad_(True)
print(a.requires_grad)

True


总结 pytorch 张量的数据结构形式