# 张量和数据类型

In [1]:
import torch
import numpy as np

## 初始化张量

### 从Python列表初始化张量

In [2]:
t = torch.tensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


In [3]:
t = torch.tensor([1., 2., 3.])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [4]:
t = torch.FloatTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [5]:
t = torch.LongTensor([1, 2, 3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


### 从numpy的ndarray初始化

In [6]:
np_array = np.arange(12).reshape(3, 4)
np_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
t = torch.from_numpy(np_array)
# 也可以使用下面的方式
# t = torch.tensor(np_array)
print(t)
print(t.dtype)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]], dtype=torch.int32)
torch.int32


## 张量（Tensor）基本数据类型

* 32位浮点型：torch.float32 / torch.float
* 64位浮点型：torch.float64
* 64位整型： torch.int64 / torch.long
* 32位整型： torch.int32
* 16位整型： torch.int16

In [8]:
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [9]:
t = torch.tensor([1, 2, 3], dtype=torch.float)
print(t)
print(t.dtype)

tensor([1., 2., 3.])
torch.float32


In [10]:
t = torch.tensor([1, 2, 3], dtype=torch.long)
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64


## 创建随机值张量

In [11]:
# 创建（0，1）之间均匀分布的随机数
t = torch.rand(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[0.4860, 0.3687, 0.2372, 0.5329],
        [0.4784, 0.6122, 0.6382, 0.6685],
        [0.7707, 0.8564, 0.8704, 0.6532]])
torch.float32
torch.Size([3, 4])


In [12]:
# 创建标准正态分布的随机数
t = torch.randn(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[-0.3052, -0.2343, -2.2471,  0.6742],
        [-0.2385, -1.2642, -0.7632, -0.6994],
        [-0.3246, -0.7096,  0.8201, -0.3390]])
torch.float32
torch.Size([3, 4])


In [13]:
# 创建全0的张量
t = torch.zeros(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.float32
torch.Size([3, 4])


In [14]:
# 创建全1的张量
t = torch.ones(3, 4)
print(t)
print(t.dtype)
print(t.shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32
torch.Size([3, 4])


In [15]:
# 创建一个与t形状相同的张量，但是值是正态分布的随机数
t = torch.randn_like(t)
print(t)
print(t.dtype)
print(t.shape)

tensor([[-1.4096, -0.6351, -0.1989,  0.6484],
        [-1.2685, -2.0016,  0.8828, -1.0057],
        [ 1.5341, -1.2712,  1.3198,  0.0872]])
torch.float32
torch.Size([3, 4])


## 张量的属性

In [16]:
# 创建一个与t形状相同的张量，但是值是在（0，1）均匀分布的随机数
t = torch.rand_like(t)
print(t)
# 返回张量的数据类型
print(t.dtype)
# 返回张量的形状
print(t.shape)
print("size = " + str(t.size()))
# 返回张量的维度
print("dim = " + str(t.dim()))
# 返回张量第一个维度的长度
print("size(0) = " + str(t.size(0)))
# 返回张量第二个维度的长度
print("size(1) = " + str(t.size(1)))
# 返回张量的元素个数
print("numel= " + str(t.numel()))


tensor([[0.6398, 0.1267, 0.1516, 0.0887],
        [0.6522, 0.3207, 0.5437, 0.9627],
        [0.1954, 0.8391, 0.1070, 0.8114]])
torch.float32
torch.Size([3, 4])
size = torch.Size([3, 4])
dim = 2
size(0) = 3
size(1) = 4
numel= 12


## 张量存储设备及其转移

In [17]:
# 返回张量的存储设备
print("device = " + str(t.device))
print("torch.cuda.is_available() = " + str(torch.cuda.is_available()))
# 将张量转移到GPU
if torch.cuda.is_available():
    t = t.to('cuda')
    print("device = " + str(t.device))

device = cpu
torch.cuda.is_available() = True
device = cuda:0


In [18]:
# 将张量转移到CPU
t = t.to('cpu')
print("device = " + str(t.device))

device = cpu


## 张量数据类型的转换

In [19]:
# 对张量进行数据类型转换
t = torch.tensor([1, 2, 3], dtype=torch.float32)
print(t)
print(t.dtype)
print("----------------")
t = t.type(torch.float64)
print(t)
print(t.dtype)
print("----------------")
t = t.type(torch.int64)
print(t)
print(t.dtype)


tensor([1., 2., 3.])
torch.float32
----------------
tensor([1., 2., 3.], dtype=torch.float64)
torch.float64
----------------
tensor([1, 2, 3])
torch.int64


In [20]:
t = torch.randn(3, 4)
print(t)
print(t.dtype)
print("----------------")
# .long()方法可以将张量转换为64位整型，即int64，与t.type(torch.int64)等价
t = t.long()
print(t)
print(t.dtype)
print("----------------")
# .int()方法可以将张量转换为32位整型
# .short()方法可以将张量转换为16位整型
# .char()方法可以将张量转换为8位整型
# .byte()方法可以将张量转换为8位无符号整型

# .double()方法可以将张量转换为64位浮点型
# .float()方法可以将张量转换为32位浮点型
t = t.float()
print(t)
print(t.dtype)
print("----------------")
# .half()方法可以将张量转换为16位浮点型

# .bool()方法可以将张量转换为布尔型

tensor([[ 1.0416, -0.5953,  1.0857, -1.5836],
        [ 0.2856,  0.4203,  0.3126,  2.3779],
        [-0.6827,  1.1500,  0.3528,  2.7267]])
torch.float32
----------------
tensor([[ 1,  0,  1, -1],
        [ 0,  0,  0,  2],
        [ 0,  1,  0,  2]])
torch.int64
----------------
tensor([[ 1.,  0.,  1., -1.],
        [ 0.,  0.,  0.,  2.],
        [ 0.,  1.,  0.,  2.]])
torch.float32
----------------


## 张量运算

In [21]:
# 加法：广播原则
t1 = torch.randn(3, 4)
print(t1)
# 数值与t1相加，每个元素加3
print(t1 + 3)
print("----------------")
# 与相同形状的张量相加,对应元素相加；与不同形状的张量相加，会报错
t2 = torch.randn(3, 4)
print(t2)
# print(t1 + t2)
# print(torch.add(t1, t2))
#等同于
print(t1.add(t2))   # t1的值不变
print("----------------")
print(t1)
print(t1.add_(t2))      # t1 = t1 + t2
# t1的值改变
print(t1)
print("----------------")
# 方法后面带下划线的方法会改变调用者的值
# 类似的方法还有sub（减法）、mul（乘法）、div（除法）、pow（幂运算）、sqrt（开方）
# log（对数运算）、exp（指数运算）、abs（绝对值）、neg（取负数）、reciprocal（取倒数）
# mean（求均值）、std（求标准差）、var（求方差）、norm（求范数）
# max（求最大值）、min（求最小值）、argmax（求最大值索引）、argmin（求最小值索引）
# sum（求和）、prod（求积）、cumsum（求累加和）、cumprod（求累乘积）
# round（四舍五入）、floor（向下取整）、ceil（向上取整）、trunc（取整数部分）、frac（取小数部分）等

tensor([[-6.2446e-01,  8.8352e-01,  1.7437e+00, -6.8458e-01],
        [ 6.5891e-01, -2.3263e-03,  1.1823e+00, -2.4381e+00],
        [-2.2688e+00,  5.3536e-02, -1.0361e+00,  2.1679e+00]])
tensor([[2.3755, 3.8835, 4.7437, 2.3154],
        [3.6589, 2.9977, 4.1823, 0.5619],
        [0.7312, 3.0535, 1.9639, 5.1679]])
----------------
tensor([[-0.1454,  1.1059, -0.7089,  0.0606],
        [ 0.0947,  0.9822, -2.3898, -0.2335],
        [-1.3571, -0.8314,  1.0086,  1.3857]])
tensor([[-0.7698,  1.9894,  1.0347, -0.6239],
        [ 0.7536,  0.9799, -1.2075, -2.6716],
        [-3.6258, -0.7779, -0.0275,  3.5537]])
----------------
tensor([[-6.2446e-01,  8.8352e-01,  1.7437e+00, -6.8458e-01],
        [ 6.5891e-01, -2.3263e-03,  1.1823e+00, -2.4381e+00],
        [-2.2688e+00,  5.3536e-02, -1.0361e+00,  2.1679e+00]])
tensor([[-0.7698,  1.9894,  1.0347, -0.6239],
        [ 0.7536,  0.9799, -1.2075, -2.6716],
        [-3.6258, -0.7779, -0.0275,  3.5537]])
tensor([[-0.7698,  1.9894,  1.0347, -0.6239],
  

In [22]:
# matmul（矩阵乘法）、@（矩阵乘法）、T（转置）、transpose（转置）、permute（维度交换）、reshape（形状变换）、view（形状变换）
t1 = torch.randn(3, 4)
print(t1)
print(t1.T)
print(t1.matmul(t1.T))

tensor([[-0.4040, -0.8557, -0.7382,  0.3856],
        [ 1.2600,  0.8013, -0.5460,  0.8009],
        [ 1.2270, -0.1237,  0.5516,  1.0479]])
tensor([[-0.4040,  1.2600,  1.2270],
        [-0.8557,  0.8013, -0.1237],
        [-0.7382, -0.5460,  0.5516],
        [ 0.3856,  0.8009,  1.0479]])
tensor([[ 1.5890, -0.4829, -0.3930],
        [-0.4829,  3.1693,  1.9849],
        [-0.3930,  1.9849,  2.9230]])


## 从张量转换为python和numpy的数据类型

In [23]:
# 转换为Python数据类型
t2 = t1.sum()
print(t2)
print(t2.item())        # 将张量的值转换为Python数值
print(t1.tolist())      # 将张量的值转换为Python列表
result = t1.mean()      # 求均值
print(result)           # 返回一个张量
print(result.item())    # 返回一个Python数值

tensor(3.4067)
3.4066624641418457
[[-0.40404650568962097, -0.8556524515151978, -0.7381729483604431, 0.38560277223587036], [1.2600404024124146, 0.80130535364151, -0.5460147857666016, 0.8008570075035095], [1.2269566059112549, -0.12370836734771729, 0.5516248941421509, 1.047870397567749]]
tensor(0.2839)
0.2838885486125946


In [24]:
# 转换为Numpy数据类型
# 从Numpy数组创建张量
np_array = np.random.randn(3, 4)
print(np_array)
t = torch.from_numpy(np_array)
print(t)
# 将张量转换为Numpy数组
# .numpy()方法可以将张量转换为Numpy数组
np_array = t.numpy()
print(np_array)


[[ 1.34603901  0.72275066 -1.13441934  0.97801179]
 [-0.65498111 -0.62947032  0.71560784 -0.61951748]
 [-1.79019783 -1.32416049  0.50378579  0.9869958 ]]
tensor([[ 1.3460,  0.7228, -1.1344,  0.9780],
        [-0.6550, -0.6295,  0.7156, -0.6195],
        [-1.7902, -1.3242,  0.5038,  0.9870]], dtype=torch.float64)
[[ 1.34603901  0.72275066 -1.13441934  0.97801179]
 [-0.65498111 -0.62947032  0.71560784 -0.61951748]
 [-1.79019783 -1.32416049  0.50378579  0.9869958 ]]


## 张量的变形

In [25]:
t = torch.randn(3, 4)
print(t)
print(t.shape)
# .view()方法可以改变张量的形状，但是张量的元素个数不能改变
t1 = t.view(4, 3)
print(t1)
print(t1.shape)
# .reshape()方法与.view()方法功能相同

tensor([[-0.4553,  2.9935,  0.0671,  1.6772],
        [ 1.3228,  0.5531,  1.4230, -0.2185],
        [ 1.6426,  0.6223, -0.2198,  0.0250]])
torch.Size([3, 4])
tensor([[-0.4553,  2.9935,  0.0671],
        [ 1.6772,  1.3228,  0.5531],
        [ 1.4230, -0.2185,  1.6426],
        [ 0.6223, -0.2198,  0.0250]])
torch.Size([4, 3])


In [26]:
# 常用于展平张量
t = torch.randn(3, 4)
print(t)
print(t.shape)
# 转换为第二维度为1的张量，-1表示自动计算
t1 = t.view(-1, 1)  #即将t展平为 24 * 1 的张量
print(t1)
print(t1.shape)
# 例如
t = torch.randn(12, 3, 4, 4)
print(t.shape)
# 将t展平为 12 * 48 的张量
t1 = t.view(12, -1)
# 也可写为
t1 = t.view(12, 48)  # 12 * 3 * 4 * 4 = 12 * 48
print(t1.shape)

tensor([[-1.0168, -0.8039,  0.6670, -0.1121],
        [ 1.2239,  1.4895, -0.4935, -0.7559],
        [ 0.3140,  1.5509,  0.5233, -0.0166]])
torch.Size([3, 4])
tensor([[-1.0168],
        [-0.8039],
        [ 0.6670],
        [-0.1121],
        [ 1.2239],
        [ 1.4895],
        [-0.4935],
        [-0.7559],
        [ 0.3140],
        [ 1.5509],
        [ 0.5233],
        [-0.0166]])
torch.Size([12, 1])
torch.Size([12, 3, 4, 4])
torch.Size([12, 48])


In [27]:
# 给张量增加一个维度，例如将形状为(3, 4)的张量增加一个维度，形状变为(1, 3, 4)
t = torch.randn(3, 4)
print(t)
print(t.shape)
# .unsqueeze()方法可以增加张量为1的维度
t1 = t.unsqueeze(0) # 在第0维度增加一个维度
print(t1)
print(t1.shape)
# 也可以写为
# t1 = t.view(1, 3, 4)
# print(t1)
# print(t1.shape)

# 给张量减少一个维度
# .squeeze()方法可以减少张量为1的维度
t2 = t1.squeeze()
print(t2)
print(t2.shape)

tensor([[-0.6300, -0.1251,  0.7509, -1.7167],
        [-0.0880,  0.1965, -0.3348, -1.3354],
        [ 0.8060, -0.4016,  1.1625,  1.0843]])
torch.Size([3, 4])
tensor([[[-0.6300, -0.1251,  0.7509, -1.7167],
         [-0.0880,  0.1965, -0.3348, -1.3354],
         [ 0.8060, -0.4016,  1.1625,  1.0843]]])
torch.Size([1, 3, 4])
tensor([[-0.6300, -0.1251,  0.7509, -1.7167],
        [-0.0880,  0.1965, -0.3348, -1.3354],
        [ 0.8060, -0.4016,  1.1625,  1.0843]])
torch.Size([3, 4])


### 张量的自动微分

将Torch.Tensor属性 .requires_grad 设置为True，

pytorch将开始跟踪对此张量的所有操作。

完成计算后，可以调用 .backward() 并自动计算所有梯度。

该张量的梯度将累加到.grad属性中。

In [ ]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

In [ ]:
x.requires_grad

In [111]:
x.grad

In [112]:
x.grad_fn   # 指向运算生成此张量的方法

In [ ]:
# 进行张量运算
y = x + 2
print(y)

In [ ]:
# y是由于运算而创建的，因此具有grad_fn属性

print(y.grad_fn)

In [ ]:
# 进行更多操作

z = y * y * 3
out = z.mean()

print(z, out)

### 计算梯度

In [116]:
out.backward()    # 自动微分运算, 注意 out 是标量值

打印梯度  d（out）/ dx   

out = f(x)

In [ ]:
print(x.grad)

In [ ]:
x.data

In [107]:
x.grad_fn

当张量的 requires_grad 属性为 True 时， 

pytorch会一直跟踪记录此张量的运算

当不需要跟踪计算时，可以通过将代码块包装在  with torch.no_grad(): 上下文中

In [ ]:
print(x.requires_grad)
print((x ** 2).requires_grad)

with torch.no_grad():
    print((x ** 2).requires_grad)

也可使用 .detach() 来获得具有相同内容但不需要跟踪运算的新Tensor ：

In [ ]:
print(x.requires_grad)
y = x.detach()
print(y.requires_grad)

In [ ]:
x.data

In [ ]:
x.detach()

使用 requires_grad_ 就地改变张量此属性

In [ ]:
a = torch.randn(2, 2)
a = a*3 + 2
print(a.requires_grad)

In [ ]:
a.requires_grad_(True)
print(a.requires_grad)

总结 pytorch 张量的数据结构形式